es =
{
	"nombre" : 'Finca de Jhon Fernando',
	"nombreG" : 'Que producto compró?',
	"nombreI" : 'Que producto vendió?',
	"nombreB" : 'Qué quiere buscar?',
	"descripcion" : 'Los detalles que desee dar para buscar',
	"costoGI" : 'Cuanto valió todo?. Solo numeros',
	"costoB" : 'Precio que quiere buscar. Solo numeros',
	"fechaG" : 'Fecha de la compra. Presione click para cambiar la fecha',
	"fechaI" : 'Fecha de la venta. Presione click para cambiar la fecha',
	"ano" : 'Año que quiere buscar',
	"mes" : 'Mes que quiere buscar',
	"dia" : 'Día que quiere buscar',
	"tipo" : 'Puede buscar en cafe, ganado, cerdos, revuelto o en otros',
	"botonI" : 'Presione click para registrar la venta',
	"botonG" : 'Presione click para registrar la compra',
	"botonB" : 'Presione click para buscar',
	"principal" : 'Seleccione Principal para consultar toda la información disponible',
	"cafe" : 'Seleccione Café para consultar e ingresar toda la información relacionada con café',
	"ganado" : 'Seleccione Ganado para consultar e ingresar toda la información relacionada con ganado',
	"cerdos" : 'Seleccione Cerdos para consultar e ingresar toda la información relacionada con cerdos',
	"revuelto" : 'Seleccione Revuelto para consultar e ingresar toda la información relacionada con revuelto',
	"otros" : 'Seleccione Otros para consultar e ingresar cualquier otra información como mercado, gasolina u otros',
	"estado" : '',
	"Principal" : 'Está en la sección donde puede consultar toda la información registrada',
	"Café" : 'Está en la sección donde puede registrar información relacionada con Café',
	"Ganado" : 'Está en la sección donde puede registrar información relacionada con Ganado',
	"Cerdos" : 'Está en la sección donde puede registrar información relacionada con Cerdos',
	"Revuelto" : 'Está en la sección donde puede registrar información relacionada con Revuelto',
	"Otros" : 'Está en la sección donde puede registrar cualquer otra información',
	"Principal_m" : '',
	"Café_m" : 'cafe',
	"Ganado_m" : 'ganado',
	"Cerdos_m" : 'cerdos',
	"Revuelto_m" : 'revuelto',
	"Otros_m" : 'otros',	
}