es =
{
	"nombre" : 'Finca de Jhon Fernando',
	"nombreG" : 'Que producto compró?',
	"nombreI" : 'Que producto vendió?',
	"nombreB" : 'Qué quiere buscar?',
	"descripcion" : 'Los detalles que desee dar para buscar',
	"costoGI" : 'Cuanto valió todo?. Solo numeros',
	"costoB" : 'Precio que quiere buscar. Solo numeros',
	"fechaG" : 'Fecha de la compra. Presione click para cambiar la fecha',
	"fechaI" : 'Fecha de la venta. Presione click para cambiar la fecha',
	"ano" : 'Año que quiere buscar',
	"mes" : 'Mes que quiere buscar',
	"dia" : 'Día que quiere buscar',
	"tipo" : 'Seleccione la clasificación',
	"botonI" : 'Presione click para registrar la venta',
	"botonG" : 'Presione click para registrar la compra',
	"botonB" : 'Presione click para buscar',
	"nombreIngreso" : '',	
	"descripcionIngreso" : '',	
	"nombreGasto" : '',	
	"descripcionGasto" : '',	
	"nombreIG" : '',	
	"descripcionIG" : '',
	"opcionesIG" : [{"opcion" : 'cafe',"valor" : 'cafe'},{"opcion" : 'ganado',"valor" : 'ganado'},{"opcion" : 'cerdos',"valor" : 'cerdos'},{"opcion" : 'revuelto',"valor" : 'revuelto'},{"opcion" : 'otros',"valor" : 'otros'}],
	"opcionesB" : [{"opcion" : 'todos',"valor" : ''},{"opcion" : 'cafe',"valor" : 'cafe'},{"opcion" : 'ganado',"valor" : 'ganado'},{"opcion" : 'cerdos',"valor" : 'cerdos'},{"opcion" : 'revuelto',"valor" : 'revuelto'},{"opcion" : 'otros',"valor" : 'otros'}],
	"revisar" : 'Revisar',
	"agregado" : 'Agregado',
}