es =
{
	"titulo" : '',
	"nombreG" : 'Que producto compró?',
	"nombreI" : 'Que producto vendió?',
	"nombreB" : 'Qué quiere buscar?',
	"descripcion" : 'Los detalles que desee dar para buscar',
	"costoGI" : 'Cuanto valió todo?. Solo numeros',
	"costoB" : 'Precio que quiere buscar. Solo numeros',
	"fechaG" : 'Fecha de la compra. Presione click para cambiar la fecha',
	"fechaI" : 'Fecha de la venta. Presione click para cambiar la fecha',
	"ano" : 'Año que quiere buscar',
	"mes" : 'Mes que quiere buscar',
	"dia" : 'Día que quiere buscar',
	"tipo" : 'Seleccione la clasificación',
	"botonI" : 'Presione click para registrar la venta',
	"botonG" : 'Presione click para registrar la compra',
	"botonB" : 'Presione click para buscar',
	"botonP" : 'Presione click para pagar',
	"botonBO" : 'Presione click para borrar',
	"botonD" : 'Presione click para cambiar a estado de deuda',
	"nombreIngreso" : '',	
	"descripcionIngreso" : '',	
	"nombreGasto" : '',	
	"descripcionGasto" : '',	
	"nombreIG" : '',	
	"descripcionIG" : '',
	"dinerosB" : 'Seleccione si quiere buscar ingresos, gastos o todos',
	"fechaDesde" : 'Desde qué fecha quiere buscar',
	"fechaHasta" : 'Hasta qué fecha quiere buscar',
	"fechaPago" : 'Fecha en que se realizó el pago',
	"dineroB" : [{"dinero" :  'todos', "valor" : ''},{"dinero" :  'ingresos', "valor" : 'ingresos'},{"dinero" :  'gastos', "valor" : 'gastos'}],
	"opcionesIG" : [{"opcion" : 'cafe',"valor" : 'cafe'},{"opcion" : 'ganado',"valor" : 'ganado'},{"opcion" : 'cerdos',"valor" : 'cerdos'},{"opcion" : 'revuelto',"valor" : 'revuelto'},{"opcion" : 'otros',"valor" : 'otros'}],
	"opcionesB" : [{"opcion" : 'todos',"valor" : ''},{"opcion" : 'cafe',"valor" : 'cafe'},{"opcion" : 'ganado',"valor" : 'ganado'},{"opcion" : 'cerdos',"valor" : 'cerdos'},{"opcion" : 'revuelto',"valor" : 'revuelto'},{"opcion" : 'otros',"valor" : 'otros'}],
	"revisar" : 'Revisar',
	"revisarB" : 'Debe seleccionar ingresos o gastos, y para borrar debe ingresar id',
	"agregado" : 'Agregado',
}