version: "3.8"

networks:
  webnet: 
    driver: overlay
    attachable: true

services:
  app: 
    image: jufernando18/finca:1.0.0
    env_file: .env
    ports: 
      - $APP_PORT:80
    networks:
      - webnet
    depends_on: 
      - db
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    ports: 
      - $DB_PORT:3306
    volumes: 
      - $PWD/mysql_data:/var/lib/mysql
    networks: 
      - webnet
